### TRAINING CONFIGURATIONS ###
# dataset
dataset_dir: /informatik2/tams/home/deng/catkin_ws/src/Robot_grasp/data/adv_synth
output_dir: /informatik2/tams/home/deng/catkin_ws/src/Robot_grasp/data/savegraspNet_yuchen
model_dir: /informatik2/tams/home/deng/catkin_ws/src/Robot_grasp/data/savegraspNet_yuchen

# general optimization parameters
train_batch_size: 64
val_batch_size: 64

data_split_mode: image_wise # how to split up the data into training vs validation: options are image_wise, stable_pose_wise, object_wise
train_pct: 0.8 # percentage of the data to use for training vs validation
total_pct: 1.0 # percentage of all the files to use
eval_total_train_error: 0

loss: l2
optimizer: rmsprop
base_lr: 0.001
decay_step_multiplier: 0.8   # number of times to go through training datapoints before stepping down decay rate
decay_rate: 0.96
momentum_rate: 0.9

### GQCNN CONFIG ###
graspcnn_config:
  # basic data metrics
  im_height: 50
  im_width: 50
  im_channels: 3
  # needs to match input data mode that was used for training, determines the pose dimensions for the network
  input_data_mode: yuchen_pose_mode

  # prediction batch size, in training this will be overriden by the val_batch_size in the SGDOptimizer's config file
  batch_size: 64
  dropout_keep_prob: 0.5

  dim_grasp: 5
  num_objClasses: 34
